pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = "NeoForge"
			url = 'https://maven.neoforged.net/releases' 
		}
		maven {
			name = "Forge"
			url = 'https://maven.minecraftforge.net/' 
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

// Should match your modid
rootProject.name = 'block_finder'

include ('common')
include ('fabric')
include ('neoforge')
include('forge')