# See https://docs.minecraftforge.net/en/1.21.x/gettingstarted/modfiles/#modstoml
# There are lots of things you can do with the mods.toml, and not all fields are included with this MDK
# References: https://github.com/MinecraftForge/MDKExamples

modLoader="javafml"
loaderVersion="[11,)"
license="CC BY-NC-SA 4.0"
issueTrackerURL="https://github.com/echen0719/block-finder/issues" #optional
#clientSideOnly=true #optional, default=false

[[mods]]
modId="block_finder"
version="1.1.2"
displayName="Block Finder"
#updateJSONURL="https://example.com/updates.json" #optional
displayURL="https://echen0719.github.io/" #optional
logoFile="assets/block_finder/icon.png"
#credits="echen0719" #optional
authors="echen0719" #optional
#displayTest="MATCH_VERSION" #optional, default=MATCH_VERSION when not clientSideOnly, else IGNORE_ALL_VERSION

description="Find blocks in a singleplayer world"

[[dependencies.block_finder]] #recommended
    modId="neoforge"
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.block_finder]] #recommended
    modId="minecraft"
    mandatory=true
    versionRange="[26.2,)"
    ordering="NONE"
    side="BOTH"
